#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: 750e50d
#
Name     : mandoc
Version  : 1.14.6
Release  : 5
URL      : https://mandoc.bsd.lv/snapshots/mandoc-1.14.6.tar.gz
Source0  : https://mandoc.bsd.lv/snapshots/mandoc-1.14.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: mandoc-bin = %{version}-%{release}
Requires: mandoc-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Remove-local-from-prefix.patch

%description
No detailed description available

%package bin
Summary: bin components for the mandoc package.
Group: Binaries
Requires: mandoc-license = %{version}-%{release}

%description bin
bin components for the mandoc package.


%package license
Summary: license components for the mandoc package.
Group: Default

%description license
license components for the mandoc package.


%prep
%setup -q -n mandoc-1.14.6
cd %{_builddir}/mandoc-1.14.6
%patch -P 1 -p1
pushd ..
cp -a mandoc-1.14.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707086934
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707086934
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mandoc
cp %{_builddir}/mandoc-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/mandoc/d96759128c2e101cfcd080508b2d4ba9149d05ba || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/apropos
rm -f %{buildroot}*/usr/bin/demandoc
rm -f %{buildroot}*/usr/bin/makewhatis
rm -f %{buildroot}*/usr/bin/man
rm -f %{buildroot}*/usr/bin/soelim
rm -f %{buildroot}*/usr/bin/whatis
rm -f %{buildroot}*/usr/man/man1/apropos.1
rm -f %{buildroot}*/usr/man/man1/demandoc.1
rm -f %{buildroot}*/usr/man/man1/man.1
rm -f %{buildroot}*/usr/man/man1/soelim.1
rm -f %{buildroot}*/usr/man/man1/whatis.1
rm -f %{buildroot}*/usr/man/man5/man.conf.5
rm -f %{buildroot}*/usr/man/man5/mandoc.db.5
rm -f %{buildroot}*/usr/man/man7/eqn.7
rm -f %{buildroot}*/usr/man/man7/man.7
rm -f %{buildroot}*/usr/man/man7/mandoc_char.7
rm -f %{buildroot}*/usr/man/man7/mdoc.7
rm -f %{buildroot}*/usr/man/man7/roff.7
rm -f %{buildroot}*/usr/man/man7/tbl.7
rm -f %{buildroot}*/usr/man/man8/makewhatis.8
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/man/man1/mandoc.1

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/mandoc
/usr/bin/mandoc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mandoc/d96759128c2e101cfcd080508b2d4ba9149d05ba
